# Generated by Django 4.1 on 2022-12-07 14:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='نوع دسترسی')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='نقش')),
                ('permissions', models.ManyToManyField(to='Account.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_national_code', message='کد ملی باید 10 رقمی باشد', regex='^[0-9]{10}$')], verbose_name='کدملی')),
                ('birthdate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='شماره تلفن باید 11 رقمی باشد', regex='^[0-9]{11}$')], verbose_name='شماره تلفن')),
                ('cell_number', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن ثابت')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('national_code_picture', models.ImageField(blank=True, null=True, upload_to='./static/pictures of users', verbose_name='عکس کارت ملی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='./static/pictures of profile', verbose_name='عکس پروفایل')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.role')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
