# Generated by Django 4.2.14 on 2024-08-10 18:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTINA_Ballance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artina_eth', models.FloatField(default=0)),
                ('artina_rial', models.FloatField(default=0)),
                ('artina_matic', models.FloatField(default=0)),
                ('artina_unavailable_rial', models.FloatField(default=0)),
                ('artina_sell_ticket', models.FloatField(default=0)),
                ('artina_sell_ticket_count', models.IntegerField(default=0)),
                ('artina_3d_exhivbition', models.FloatField(default=0)),
                ('artina_3d_exhivbition_count', models.IntegerField(default=0)),
                ('artina_commision', models.FloatField(default=0)),
                ('artina_commision_count', models.IntegerField(default=0)),
                ('artina_mint', models.FloatField(default=0)),
                ('artina_mint_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('text', models.TextField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='basic', max_length=10, null=True, verbose_name='نوع دسترسی')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='rial', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shaba_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='shaba_number')),
                ('amount', models.PositiveIntegerField()),
                ('reference_number', models.PositiveIntegerField()),
                ('origin', models.CharField(blank=True, max_length=24, null=True, verbose_name='shaba_number')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=42, unique=True)),
                ('private_key', models.CharField(default=0, max_length=200, unique=True)),
                ('MATIC_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('ETH_balance', models.DecimalField(decimal_places=6, default=0, max_digits=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial_available_balance', models.IntegerField(default=0, verbose_name='mojudi')),
                ('rial_untradable_balance', models.IntegerField(default=0, verbose_name='unavailable mojudi')),
                ('matic_balance', models.FloatField(default=0)),
                ('matic_untradable_balance', models.FloatField(default=0)),
                ('eth_balance', models.FloatField(default=0)),
                ('eth_untradable_balance', models.FloatField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('side', models.CharField(choices=[('SELL', 'SELL'), ('BUY', 'BUY'), ('withdrawal', 'withdrawal'), ('deposit', 'deposit')], default='BUY', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_currency', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Account.transactioncurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TicketUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(max_length=200, null=True)),
                ('ticket_id', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='user_zero', max_length=10, null=True, verbose_name='نقش')),
                ('permissions', models.ManyToManyField(to='Account.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('national_code', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_national_code', message='کد ملی باید 10 رقمی باشد', regex='^[0-9]{10}$')], verbose_name='کدملی')),
                ('birthdate', models.CharField(max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('phone_number', models.CharField(max_length=11, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='شماره تلفن باید 11 رقمی باشد', regex='^[0-9]{11}$')], verbose_name='شماره تلفن')),
                ('phone_number_verified', models.BooleanField(default=False)),
                ('cell_number', models.CharField(max_length=11, null=True, verbose_name='شماره تلفن ثابت')),
                ('shaba_number', models.CharField(blank=True, max_length=24, null=True, verbose_name='shaba_number')),
                ('card_number', models.CharField(blank=True, max_length=16, null=True, verbose_name='card_number')),
                ('address', models.TextField(max_length=200, null=True, verbose_name='آدرس')),
                ('national_card_picture', models.TextField(default='', null=True, verbose_name='عکس کارت ملی')),
                ('profile_picture', models.TextField(default='http://api.artina.org/static/images/default_C7876ge.webp', null=True, verbose_name='عکس پروفایل')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='ایمیل')),
                ('email_verified', models.BooleanField(default=False)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='postal_code')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='biography')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_foreigner', models.BooleanField(default=False)),
                ('role', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Account.role')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField(max_length=200, null=True)),
                ('message_seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=35)),
                ('verification_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
