# Generated by Django 4.0.6 on 2022-08-15 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='نقش')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='نقش')),
                ('permissions', models.ManyToManyField(to='Account.permission')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nationalcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='کدملی')),
                ('birthdate', models.CharField(blank=True, max_length=10, null=True, verbose_name='تاریخ تولد')),
                ('phonenumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تلفن')),
                ('cellnumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='ثابت شماره تلفن')),
                ('address', models.TextField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('national_code_picture', models.ImageField(blank=True, null=True, upload_to='pictures of users', verbose_name='عکس کارت ملی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='عکس پروفایل', verbose_name='عکس پروفایل')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Account.role')),
            ],
        ),
    ]
