# Generated by Django 4.1 on 2022-09-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/pictures of profile', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='national_code_picture',
            field=models.ImageField(blank=True, null=True, upload_to='./static/pictures of users', verbose_name='عکس کارت ملی'),
        ),
    ]
