# Generated by Django 4.0.6 on 2022-08-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cellnumber',
            new_name='cell_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='nationalcode',
            new_name='national_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phonenumber',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(max_length=10, verbose_name='نوع دسترسی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures of profile', verbose_name='عکس پروفایل'),
        ),
    ]
