# Generated by Django 4.1 on 2024-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='card_number'),
        ),
    ]
