# Generated by Django 4.1 on 2023-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='postal_code'),
        ),
        migrations.AddField(
            model_name='userbalance',
            name='eth_unavailable_balance',
            field=models.FloatField(default=0, verbose_name='eth_unavailable_balance'),
        ),
    ]
