# Generated by Django 4.1 on 2024-07-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_profile_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='', null=True, verbose_name='عکس پروفایل'),
        ),
    ]
