# Generated by Django 4.1 on 2023-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_card_picture',
            field=models.TextField(default='default.png', null=True, verbose_name='عکس کارت ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='default.png', null=True, verbose_name='عکس پروفایل'),
        ),
    ]
