# Generated by Django 4.1 on 2024-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_card_picture',
            field=models.TextField(default='', null=True, verbose_name='عکس کارت ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='http://api.artina.org/static/images/default_C7876ge.webp', null=True, verbose_name='عکس پروفایل'),
        ),
    ]
