# Generated by Django 4.1 on 2023-05-08 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Account', '0003_alter_profile_national_card_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='eth', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='deposit', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTurnover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_value', models.IntegerField(default=0, verbose_name='volume')),
                ('transaction_currency', models.ForeignKey(default='rial', on_delete=django.db.models.deletion.CASCADE, to='Account.transactioncurrency')),
                ('transaction_type', models.ForeignKey(default='deposit', on_delete=django.db.models.deletion.CASCADE, to='Account.transactiontype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rial_available_balance', models.IntegerField(default=0, verbose_name='mojudi')),
                ('rial_untradable_balance', models.IntegerField(default=0, verbose_name='unavailable mojudi')),
                ('eth_bllance', models.IntegerField(default=0, verbose_name='mojudi etherium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
