# Generated by Django 4.1 on 2023-08-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(default=0, max_length=42, unique=True),
        ),
    ]
