# Generated by Django 4.1 on 2023-05-08 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_transactioncurrency_transactiontype_userturnover_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbalance',
            old_name='eth_bllance',
            new_name='eth_balance',
        ),
    ]
