# Generated by Django 4.1 on 2024-07-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_profile_national_card_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARTINA_Ballance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artina_eth', models.FloatField(default=0)),
                ('artina_rial', models.FloatField(default=0)),
                ('artina_matic', models.FloatField(default=0)),
                ('artina_unavailable_rial', models.FloatField(default=0)),
                ('artina_sell_ticket', models.FloatField(default=0)),
                ('artina_sell_ticket_count', models.IntegerField(default=0)),
                ('artina_3d_exhivbition', models.FloatField(default=0)),
                ('artina_3d_exhivbition_count', models.IntegerField(default=0)),
                ('artina_commision', models.FloatField(default=0)),
                ('artina_commision_count', models.IntegerField(default=0)),
                ('artina_mint', models.FloatField(default=0)),
                ('artina_mint_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='card_number'),
        ),
    ]
