# Generated by Django 4.1 on 2023-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_wallet_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='private_key',
            field=models.CharField(default=0, max_length=200, unique=True),
        ),
    ]
