# Generated by Django 4.1 on 2023-05-13 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_rename_eth_bllance_userbalance_eth_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='verified',
        ),
    ]
