# Generated by Django 4.1 on 2023-11-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_alter_wallet_private_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_verified',
            field=models.BooleanField(default=False),
        ),
    ]
