# Generated by Django 4.1 on 2023-05-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_phoneverification_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_card_picture',
            field=models.TextField(default='http://api.artina.org/static/images/NC.png', null=True, verbose_name='عکس کارت ملی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.TextField(default='http://api.artina.org/static/images/default_C7876ge.webp', null=True, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='transactioncurrency',
            name='name',
            field=models.CharField(default='rial', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='rial_available_balance',
            field=models.IntegerField(default=100000, verbose_name='mojudi'),
        ),
    ]
