# Generated by Django 4.1 on 2023-06-05 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_profile_national_card_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='card_number'),
        ),
    ]
