# Generated by Django 4.1 on 2023-06-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0008_profile_card_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='shaba_number'),
        ),
    ]
