# Generated by Django 4.1 on 2023-06-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0009_remove_profile_card_number_profile_shaba_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='shaba_number'),
        ),
    ]
