# Generated by Django 4.1 on 2023-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0011_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userturnover',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
