# Generated by Django 4.1 on 2023-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0012_userturnover_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=50, null=True, verbose_name='ایمیل'),
        ),
    ]
