# Generated by Django 4.1 on 2023-06-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0013_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_card_picture',
            field=models.TextField(default='http://78.38.35.216:8000/media/mr.png', null=True, verbose_name='عکس کارت ملی'),
        ),
    ]
