# Generated by Django 4.1 on 2023-06-10 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0014_alter_profile_national_card_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_card_picture',
            field=models.TextField(default='http://78.38.35.249:8000/static/images/Fig.png', null=True, verbose_name='عکس کارت ملی'),
        ),
    ]
