# Generated by Django 4.1 on 2023-06-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0015_alter_profile_national_card_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userticket',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
