# Generated by Django 4.1 on 2023-06-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0016_userticket_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userticket',
            name='date',
        ),
        migrations.AlterField(
            model_name='userticket',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='text',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userticket',
            name='ticket_id',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
