# Generated by Django 4.1 on 2022-12-27 23:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('creator', models.CharField(max_length=15)),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('last_price', models.IntegerField(verbose_name='آخرین قیمت')),
                ('base64_image', models.TextField(default='data:image')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع مزایده')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان مزایده')),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='wallet address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(verbose_name='قیمت')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('status', models.CharField(choices=[(0, 'open'), (1, 'close')], max_length=5)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nft', models.ManyToManyField(to='core.nft')),
            ],
        ),
        migrations.CreateModel(
            name='NFTReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('review', models.TextField(blank=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='core.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
