# Generated by Django 4.1 on 2023-06-30 18:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('creator', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('last_price', models.IntegerField(verbose_name='آخرین قیمت')),
                ('image_url', models.TextField(default='data:image')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع مزایده')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان مزایده')),
                ('is_for_sale', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('external_link', models.URLField(blank=True, null=True)),
                ('author_address', models.CharField(default='0x2293221D7c357FB04De9c7D0dEeBcA427407429D', max_length=45, null=True)),
                ('in_exhibition', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='static/pdfs/')),
                ('url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='wallet address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.IntegerField(verbose_name='قیمت')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'close')])),
                ('report', models.IntegerField(choices=[(0, 'unsuccessful'), (1, 'successful'), (2, 'pending')], default=2)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nft')),
            ],
        ),
        migrations.CreateModel(
            name='NFTReviewRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('review', models.TextField(blank=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='core.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
