# Generated by Django 4.1 on 2024-07-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, default='other', max_length=20, null=True, verbose_name=' دسته بندی  '),
        ),
    ]
