# Generated by Django 4.1 on 2023-07-04 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='last_price',
            field=models.FloatField(verbose_name='آخرین قیمت'),
        ),
    ]
