# Generated by Django 4.1 on 2023-05-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='author_address',
            field=models.CharField(default='0x2293221D7c357FB04De9c7D0dEeBcA427407429D', max_length=45, null=True),
        ),
    ]
