# Generated by Django 4.0.6 on 2022-08-15 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftex',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 9, 19, 27, 421511), verbose_name='تاریخ پایان مزایده'),
        ),
        migrations.AddField(
            model_name='nftex',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 9, 19, 27, 421490), verbose_name='تاریخ شروع مزایده'),
        ),
    ]
