# Generated by Django 4.1 on 2024-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='side',
            field=models.CharField(choices=[('CRYPTO', 'CRYPTO'), ('TMN', 'TMN')], default='TMN', max_length=10),
        ),
    ]
