# Generated by Django 4.0.6 on 2022-08-15 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_nftex_end_date_nftex_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nftex',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 9, 20, 9, 343728, tzinfo=utc), verbose_name='تاریخ پایان مزایده'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 9, 20, 9, 343671, tzinfo=utc), verbose_name='تاریخ شروع مزایده'),
        ),
    ]
