# Generated by Django 4.1 on 2023-07-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_nft_last_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='has_physical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nft',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
