# Generated by Django 4.1 on 2022-09-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nftreviewrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
