# Generated by Django 4.1 on 2023-07-26 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_nft_has_physical_nft_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFTRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False)),
                ('review', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nft',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='NFTReviewRating',
        ),
        migrations.AddField(
            model_name='nftrating',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nft', to='core.nft'),
        ),
        migrations.AddField(
            model_name='nftrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
