# Generated by Django 4.1 on 2023-05-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_myimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nft',
            old_name='base64_image',
            new_name='image_url',
        ),
    ]
