# Generated by Django 4.1 on 2023-08-27 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nftrating_nft_share_count_nft_view_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
