# Generated by Django 4.0.6 on 2022-08-15 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
        ('core', '0004_alter_nftex_end_date_alter_nftex_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Exhibition', verbose_name='Exhibition'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='lastPrice',
            field=models.IntegerField(verbose_name='آخرین قیمت'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 10, 18, 38, 213736, tzinfo=utc), verbose_name='تاریخ پایان مزایده'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='exhibition.exhibition'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='floor_price',
            field=models.IntegerField(verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 10, 18, 38, 213712, tzinfo=utc), verbose_name='تاریخ شروع مزایده'),
        ),
    ]
