# Generated by Django 4.1 on 2023-10-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='blockHash',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='blockNumber',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='transactionHash',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='transactionIndex',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
