# Generated by Django 4.0.6 on 2022-08-15 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nft_image_alter_nft_lastprice_alter_nftex_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='NFTS'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 10, 20, 29, 126832, tzinfo=utc), verbose_name='تاریخ پایان مزایده'),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 15, 10, 20, 29, 126809, tzinfo=utc), verbose_name='تاریخ شروع مزایده'),
        ),
    ]
