# Generated by Django 4.1 on 2023-05-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_base64_image_nft_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ'),
        ),
    ]
