# Generated by Django 4.1 on 2023-12-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_nft_blockhash_nft_blocknumber_nft_transactionhash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='other', max_length=10, null=True, verbose_name=' دسته بندی  ')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.category'),
        ),
    ]
