# Generated by Django 4.0.6 on 2022-08-17 07:14

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_nft_image_alter_nftex_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 7, 14, 23, 336235, tzinfo=utc), verbose_name='تاریخ پایان مزایده'),
        ),
        migrations.AddField(
            model_name='nft',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 7, 14, 23, 336203, tzinfo=utc), verbose_name='تاریخ شروع مزایده'),
        ),
        migrations.AlterField(
            model_name='order',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nft'),
        ),
        migrations.DeleteModel(
            name='NFtEx',
        ),
    ]
