# Generated by Django 4.0.6 on 2022-08-22 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nft_end_date_nft_start_date_alter_order_nft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='lastPrice',
            field=models.IntegerField(default=0, verbose_name='آخرین قیمت'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان مزایده'),
        ),
        migrations.AlterField(
            model_name='nft',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع مزایده'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='nft',
        ),
        migrations.AddField(
            model_name='order',
            name='nft',
            field=models.ManyToManyField(to='core.nft'),
        ),
    ]
