# Generated by Django 4.1 on 2024-01-23 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_category_nft_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='other', max_length=10, null=True, verbose_name=' مجموعه')),
            ],
        ),
        migrations.AddField(
            model_name='nft',
            name='traits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nft',
            name='collection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.collection'),
        ),
    ]
