# Generated by Django 4.1 on 2023-05-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nft_token_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
