# Generated by Django 4.1 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_nft_is_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'close')]),
        ),
    ]
