# Generated by Django 4.1 on 2023-05-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='in_exhibition',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='order',
            name='nft',
        ),
        migrations.AddField(
            model_name='order',
            name='nft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nft'),
            preserve_default=False,
        ),
    ]
