# Generated by Django 4.1 on 2023-06-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='report',
            field=models.IntegerField(choices=[(0, 'unsuccessful'), (1, 'successful'), (2, 'pending')], default=2),
        ),
    ]
