# Generated by Django 4.1 on 2023-06-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='creator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nft',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
