# Generated by Django 4.0.6 on 2022-08-15 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketName', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Exhibition', verbose_name='Exhibition')),
                ('startdate', models.DateTimeField(verbose_name='تاریخ')),
                ('enddate', models.DateTimeField(verbose_name='تاریخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
