# Generated by Django 4.0.6 on 2022-08-29 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketName', models.CharField(max_length=15)),
                ('image', models.ImageField(blank=True, null=True, upload_to='./pictures of Exhibitions', verbose_name='Exhibition')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NFtEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('commission', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('is_nft_viewed_by_exhibitor', models.BooleanField(default=False)),
                ('is_nft_accepted_by_exhibitor', models.BooleanField(default=False)),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nftex', to='exhibition.exhibition')),
                ('nfts', models.ManyToManyField(related_name='nftexs', to='core.nft')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastPrice', models.IntegerField(default=0, verbose_name='آخرین قیمت')),
                ('seller', models.CharField(max_length=15)),
                ('buyer', models.CharField(max_length=15)),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('nftex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exhibition.nftex')),
            ],
        ),
    ]
