# Generated by Django 4.1 on 2024-05-27 10:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='سایر', max_length=25, verbose_name='دسته بندی')),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketName', models.CharField(max_length=35)),
                ('image', models.TextField(blank=True, null=True, verbose_name='Exhibition')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(verbose_name='تاریخ پایان')),
                ('description', models.TextField(blank=True, null=True)),
                ('has_ticket', models.BooleanField(default=False, null=True)),
                ('contract', models.TextField(blank=True, null=True, verbose_name='contract')),
                ('application_deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('commision', models.IntegerField(blank=True, default=10, verbose_name='درصد سود')),
                ('price', models.IntegerField(blank=True, default=20000, null=True, validators=[django.core.validators.MinValueValidator(5000)])),
                ('has_metaverse', models.BooleanField(default=False, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exhibition.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField(default=1000, verbose_name='ticket_id')),
                ('expiration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='exhibition.exhibition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ex_Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('authority', models.CharField(max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='exhibition.exhibition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_accepted', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, default='my application is complete')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exhibition.exhibition')),
                ('nft', models.ManyToManyField(related_name='applications', to='core.nft')),
            ],
        ),
    ]
