# Generated by Django 4.0.6 on 2022-08-17 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nft_end_date_nft_start_date_alter_order_nft_and_more'),
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Exhibition-images', verbose_name='Exhibition'),
        ),
        migrations.CreateModel(
            name='NFtEx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاریخ')),
                ('ex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nfts', to='exhibition.exhibition')),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nft')),
            ],
        ),
    ]
