# Generated by Django 4.1 on 2023-12-28 21:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='price',
            field=models.IntegerField(blank=True, default=20000, null=True, validators=[django.core.validators.MinValueValidator(5000)]),
        ),
    ]
