# Generated by Django 4.1 on 2023-05-16 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_nft_in_exhibition_remove_order_nft_order_nft'),
        ('exhibition', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_accepted', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(blank=True, null=True)),
                ('ignored', models.BooleanField(default=False)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='nft',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='nftex',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='application_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='end_date',
            field=models.DateTimeField(verbose_name='تاریخ پایان'),
        ),
        migrations.DeleteModel(
            name='NFtEx',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AddField(
            model_name='application',
            name='exhibition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='exhibition.exhibition'),
        ),
        migrations.AddField(
            model_name='application',
            name='nft',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='application', to='core.nft'),
        ),
    ]
