# Generated by Django 4.1 on 2024-01-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_remove_ticket_price_exhibition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='has_metaverse',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
