# Generated by Django 4.0.6 on 2022-08-22 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_alter_exhibition_image_nftex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='startdate',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان'),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع'),
        ),
        migrations.AddField(
            model_name='nftex',
            name='is_nft_accepted_by_exhibitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nftex',
            name='is_nft_viewed_by_exhibitor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./pictures of Exhibitions', verbose_name='Exhibition'),
        ),
    ]
