# Generated by Django 4.0.6 on 2022-08-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_alter_transaction_buyer_alter_transaction_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftex',
            name='is_nft_accepted_by_exhibitor',
        ),
        migrations.RemoveField(
            model_name='nftex',
            name='is_nft_viewed_by_exhibitor',
        ),
        migrations.AddField(
            model_name='nftex',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='ex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nftexs', to='exhibition.exhibition'),
        ),
    ]
