# Generated by Django 4.1 on 2023-05-21 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0002_application_remove_transaction_buyer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exhibition.category'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Exhibition'),
        ),
    ]
