# Generated by Django 4.0.6 on 2022-08-27 06:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_end_date_transaction_lastprice_and_more'),
        ('exhibition', '0003_remove_exhibition_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftex',
            name='commission',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='nftex',
            name='nft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition', to='core.nft'),
        ),
    ]
