# Generated by Django 4.1 on 2022-09-05 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exhibition', '0003_remove_nftex_is_nft_accepted_by_exhibitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_seller_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
