# Generated by Django 4.0.6 on 2022-08-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exhibition', '0003_remove_nftex_is_nft_accepted_by_exhibitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='nft',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.nft'),
        ),
    ]
