# Generated by Django 4.1 on 2022-09-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_alter_transaction_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/pictures of Exhibitions', verbose_name='Exhibition'),
        ),
    ]
