# Generated by Django 4.1 on 2023-05-21 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_alter_exhibition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exhibition.category'),
        ),
    ]
