# Generated by Django 4.1 on 2022-09-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0005_alter_exhibition_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ'),
        ),
    ]
