# Generated by Django 4.1 on 2023-05-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_nft_in_exhibition_remove_order_nft_order_nft'),
        ('exhibition', '0005_alter_exhibition_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='nft',
        ),
        migrations.AddField(
            model_name='application',
            name='nft',
            field=models.ManyToManyField(to='core.nft'),
        ),
    ]
