# Generated by Django 4.1 on 2023-05-24 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0006_remove_application_nft_application_nft'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default='my application is complete'),
        ),
    ]
