# Generated by Django 4.1 on 2023-05-24 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_nft_in_exhibition_remove_order_nft_order_nft'),
        ('exhibition', '0007_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='nft',
            field=models.ManyToManyField(related_name='applications', to='core.nft'),
        ),
    ]
