# Generated by Django 4.0.6 on 2022-09-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_transaction_nft'),
        ('exhibition', '0007_exreviewrating'),
    ]

    operations = [
    ]
