# Generated by Django 4.1 on 2023-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0008_alter_application_nft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='accepted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ignored',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
    ]
