# Generated by Django 4.1 on 2023-05-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0009_remove_application_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(blank=True, default='my application is complete'),
        ),
    ]
