# Generated by Django 4.0.6 on 2022-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0009_ticket_exhibition_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='nftex',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
