# Generated by Django 4.1 on 2023-06-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0010_alter_application_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibition',
            name='exhibition_id',
        ),
    ]
