# Generated by Django 4.1 on 2022-09-16 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0010_nftex_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='contract',
            field=models.FileField(null=True, upload_to='./static/contract files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
