# Generated by Django 4.1 on 2023-06-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0011_remove_exhibition_exhibition_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibition',
            name='contract',
            field=models.TextField(blank=True, null=True, verbose_name='contract'),
        ),
    ]
