# Generated by Django 4.1 on 2023-06-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0012_alter_exhibition_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='ticket_price',
            field=models.IntegerField(default=10000, verbose_name='قیمت'),
        ),
    ]
