# Generated by Django 4.1 on 2023-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0013_exhibition_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='commision',
            field=models.IntegerField(blank=True, default=10, verbose_name='درصد سود'),
        ),
    ]
