# Generated by Django 4.1 on 2023-06-20 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0014_exhibition_commision'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='exhibition_id',
            new_name='exhibition',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='ticket_price',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_count',
        ),
        migrations.AddField(
            model_name='ticket',
            name='expiration_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان'),
        ),
    ]
