# Generated by Django 4.1 on 2023-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0015_rename_exhibition_id_ticket_exhibition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='has_ticket',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
