"""
Django settings for ARTINA project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jwb9-)x##t=b#g9(cu)qz9#$-v9!r)olg0pl2p9-t4s!6syp#*'
# Retrieve variables
COMPANY_WALLET_ADDRESS = os.getenv('COMPANY_WALLET_ADDRESS')
COMPANY_WALLET_PRIVATE_KEY = os.getenv('COMPANY_WALLET_PRIVATE_KEY')
PRIVATE_KEY = os.getenv('PRIVATE_KEY')
SECRET_t_KEY = os.getenv('SECRET_T_KEY')
X_API_KEY = os.getenv('X_API_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Account',
    'exhibition',
    'core',
    'AI', 
    'game',   
    'supervisor',    
    'rest_framework',
    'corsheaders',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'Account.middleware.FailedLoginMiddleware',
    # 'Account.middleware.PaymentLoggingMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',

    
    ]
JAZZMIN_SETTINGS = {
    "title": "Artina Admin",
    "site_title": "Artina Admin",
    "site_header": "Artina",
    
    # logo for your project (defaults to static/jazzmin/img/default.png)
    "site_logo": "my_project/img/logo.png",
    
    # Set the link for the logo (defaults to admin:index)
    "site_logo_url": "/admin/",
    
    # Add related model counts (ForeignKey and OneToOne included)
    "related_modal_active": True,
    
    # More options here: https://github.com/farridav/django-jazzmin#jazzmin-settings
}
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",  # navbar-light or navbar-dark
    "accent": "accent-primary",  # primary, secondary, etc.
    
    # Configure the side menu (order, grouping, and titles)
    "order_with_respect_to": ["myapp", "otherapp"],
    "custom_links": {
        "myapp": [{"name": "Make Payment", "url": "make_payment"}],
    },
    "related_modal_active": False,
    
    # More options here: https://github.com/farridav/django-jazzmin#ui-tweaks
}

#CORS_ALLOWED_ORIGINS = [
#    'http://0.0.0.0:3000'
#]
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',  
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

REST_FRAMEWORK = {

    'DEFAULT_AUTHENTICATION_CLASSES': (

        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )

}



from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=59),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
}

ROOT_URLCONF = 'ARTINA.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ARTINA.wsgi.application'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file_login': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'login_api.log',  # File for login API logs
            'formatter': 'verbose',
        },
        'file_register': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'register_api.log',  # File for registration API logs
            'formatter': 'verbose',
            'delay': True,
        },
        'file_transferInside': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'transferInside.log',  # File for transferInside logs
            'formatter': 'verbose',
        },
        'file_payment': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'payment.log',  # File for payment logs
            'formatter': 'verbose',
        },
        'file_nft': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'nft.log',  # File for NFT logs
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': [],
            'level': 'DEBUG',
            'propagate': True,
        },
        'Account.login': {
            'handlers': ['file_login'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'Account.register': {
            'handlers': ['file_register'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core.transferInside': {
            'handlers': ['file_transferInside'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'Account.payment': {
            'handlers': ['file_payment'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core.nft': {
            'handlers': ['file_nft'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

# Postgres Database with setting the location of the database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'artina',
        'USER': 'administrator',
        'PASSWORD': 'drmNi80!prhLiPVPt@Ly',
        'HOST': 'localhost',
        'PORT': '',
        'TEST': {
            'NAME': 'mytestdatabase',
        }, }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'documentation/database/db_test.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Set the timezone to Iran/Tehran
TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
STATIC_URL = '/static/'
