# Generated by Django 4.1 on 2024-08-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergameprofile',
            name='profile_picture',
            field=models.TextField(default='http://api.artina.org/static/images/default_C7876ge.webp', null=True, verbose_name='عکس پروفایل'),
        ),
    ]
